spring:
  profiles: default
  datasource:
    driver-class:
      name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/challenge
    username: root
---
spring:
  profiles: default-postgres
  datasource:
    url: 'jdbc:postgresql://localhost:5432/challenge'
    driver-class-name: 'org.postgresql.Driver'
    username: 'sarasa'
    password: 'sarasa'
    test-on-borrow: true
    validation-query: 'SELECT 1'
    log-validation-errors: true
    max-active: 20
    initial-size: 4
    autoReconnect: true
    autoReconnectForPools: true
    is-connection-validation-required: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

